### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tancheng** [tancheng/asap#1]
- [x] Disable unrolling and tiling.
- [x] Include functional units with different precision support in the DSE.
- [x] Refine `isMultiCycleExec()`.
- [x] Include precision into `resultUpdate()` for area/power/timing estimation.
- [x] Find a way to calculate precision for each DFG.
- [x] Avoid fuse the DFGNode with different precision candidates.
- [x] Collect error rate for different kernels with various precision type support.
- [x] Collect area/power/timing statistics for different functional units using [mflowgen](https://github.com/mflowgen/mflowgen).
